package com.recruitment.app.entity;


import lombok.*;

import javax.persistence.*;

@Entity
@Table(name="User_Role_Management")
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserManagement {

    @Id
//    IN ORACLE DB ID IS GENERATED BY DEFINED SEQUENCE AND TRIGGER IN DB SCHEMA
    @SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "USER_ID_SEQ",allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "SequenceIdGenerator")
    private Integer userId;

    private String emailId;

    private String userName;

    private String userRole;

    private String dmMailId;

    private String clients;

    private String managerMailId;

    private String region;

    private String password;

    private String isFirstLogin;

    private String contactNumber;
}
