server:
  port: 8085
  servlet:
    context-path: /recruitment-app

spring:
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: APPUSER
    password: suki123
#    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: demomail2326@gmail.com
    password: kpulwufccjhpbvvl
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true



# properties for sending mail
email.from: demomail2326@gmail.com
